org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
#drivedeckBaseUrl=http://10.0.2.2:3000
# Optional override. Leave blank to let the backend return your LAN IP for the pairing page.
#drivedeckPairingUrl=

#drivedeckBaseUrl=http://192.168.1.4:3000
drivedeckBaseUrl=https://drivedeck-app.onrender.com
drivedeckPairingUrl=https://kaustubhmokashi.com/drivedeck/remote.html
